"""add vpp tables

Revision ID: 46e4ea651319
Revises: 
Create Date: 2026-01-25 17:28:16.693295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e4ea651319'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjustable_loads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_name', sa.String(length=200), nullable=False, comment='设备名称'),
    sa.Column('equipment_type', sa.String(length=100), nullable=True, comment='设备类型'),
    sa.Column('rated_power', sa.Float(), nullable=False, comment='额定功率 kW'),
    sa.Column('adjustable_ratio', sa.Float(), nullable=False, comment='可调节比例 %'),
    sa.Column('response_time', sa.Integer(), nullable=True, comment='响应时间 分钟'),
    sa.Column('adjustment_cost', sa.Float(), nullable=True, comment='调节成本 元/次'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False, comment='月份 YYYY-MM格式'),
    sa.Column('total_consumption', sa.Float(), nullable=False, comment='月度总用电量 kWh'),
    sa.Column('peak_consumption', sa.Float(), nullable=True, comment='峰段用电量 kWh'),
    sa.Column('valley_consumption', sa.Float(), nullable=True, comment='谷段用电量 kWh'),
    sa.Column('flat_consumption', sa.Float(), nullable=True, comment='平段用电量 kWh'),
    sa.Column('max_demand', sa.Float(), nullable=True, comment='最大需量 kW'),
    sa.Column('power_factor', sa.Float(), nullable=True, comment='功率因数'),
    sa.Column('total_cost', sa.Float(), nullable=False, comment='月度总电费 元'),
    sa.Column('basic_fee', sa.Float(), nullable=True, comment='基本电费 元'),
    sa.Column('market_purchase_fee', sa.Float(), nullable=True, comment='市场化购电电费 元'),
    sa.Column('transmission_fee', sa.Float(), nullable=True, comment='输配电费 元'),
    sa.Column('system_operation_fee', sa.Float(), nullable=True, comment='系统运行费 元'),
    sa.Column('government_fund', sa.Float(), nullable=True, comment='政府性基金及附加 元'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electricity_bills_month'), 'electricity_bills', ['month'], unique=False)
    op.create_table('electricity_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_type', sa.Enum('PEAK', 'VALLEY', 'FLAT', name='timeperiodtype'), nullable=False, comment='时段类型'),
    sa.Column('price', sa.Float(), nullable=False, comment='单价 元/kWh'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='开始时间 HH:MM'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='结束时间 HH:MM'),
    sa.Column('effective_date', sa.Date(), nullable=True, comment='生效日期'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load_curves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='时间戳 (15分钟间隔)'),
    sa.Column('load_value', sa.Float(), nullable=False, comment='负荷值 kW'),
    sa.Column('date', sa.Date(), nullable=False, comment='日期'),
    sa.Column('time_period', sa.Enum('PEAK', 'VALLEY', 'FLAT', name='timeperiodtype'), nullable=True, comment='时段类型 (峰/平/谷)'),
    sa.Column('is_workday', sa.Boolean(), nullable=True, comment='是否工作日'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_load_curves_date'), 'load_curves', ['date'], unique=False)
    op.create_index(op.f('ix_load_curves_timestamp'), 'load_curves', ['timestamp'], unique=False)
    op.create_table('vpp_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.Float(), nullable=False, comment='配置值'),
    sa.Column('config_unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpp_configs_config_key'), 'vpp_configs', ['config_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpp_configs_config_key'), table_name='vpp_configs')
    op.drop_table('vpp_configs')
    op.drop_index(op.f('ix_load_curves_timestamp'), table_name='load_curves')
    op.drop_index(op.f('ix_load_curves_date'), table_name='load_curves')
    op.drop_table('load_curves')
    op.drop_table('electricity_prices')
    op.drop_index(op.f('ix_electricity_bills_month'), table_name='electricity_bills')
    op.drop_table('electricity_bills')
    op.drop_table('adjustable_loads')
    # ### end Alembic commands ###
