"""添加网关和数据源模型

Revision ID: dcc5c9c7516c
Revises: 3744d2b3634e
Create Date: 2026-02-15 16:37:17.655130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc5c9c7516c'
down_revision: Union[str, None] = '3744d2b3634e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasource_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=False, comment='数据源 ID'),
    sa.Column('point_id', sa.Integer(), nullable=True, comment='关联 Point 表 ID'),
    sa.Column('address', sa.String(length=100), nullable=False, comment='协议地址'),
    sa.Column('data_type', sa.String(length=30), nullable=True, comment='数据类型: int16/uint16/int32/float32/bool/string'),
    sa.Column('scale', sa.Float(), nullable=True, comment='缩放系数'),
    sa.Column('offset', sa.Float(), nullable=True, comment='偏移量'),
    sa.Column('enum_mapping', sa.JSON(), nullable=True, comment='枚举映射 JSON'),
    sa.Column('is_dry_contact', sa.Boolean(), nullable=True, comment='是否干接点类型'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datasource_id', 'address', name='uq_datasource_point_address')
    )
    op.create_table('datasources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='数据源名称'),
    sa.Column('protocol_type', sa.String(length=30), nullable=False, comment='协议类型'),
    sa.Column('gateway_id', sa.Integer(), nullable=True, comment='关联网关 ID'),
    sa.Column('connection_config', sa.JSON(), nullable=False, comment='连接配置'),
    sa.Column('collection_interval', sa.Integer(), nullable=True, comment='采集周期（秒）1-60'),
    sa.Column('write_enabled', sa.Boolean(), nullable=True, comment='是否允许写入'),
    sa.Column('status', sa.String(length=30), nullable=True, comment='连接状态'),
    sa.Column('last_communication', sa.DateTime(), nullable=True, comment='最后通信时间'),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True, comment='连续失败次数'),
    sa.Column('retry_base_delay', sa.Float(), nullable=True, comment='重试基础延迟（秒）'),
    sa.Column('retry_max_delay', sa.Float(), nullable=True, comment='重试最大延迟（秒）'),
    sa.Column('retry_max_failures', sa.Integer(), nullable=True, comment='连续失败阈值'),
    sa.Column('site_id', sa.Integer(), nullable=True, comment='站点 ID'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_datasources_gateway_enabled', 'datasources', ['gateway_id', 'is_enabled'], unique=False)
    op.create_table('gateways',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gateway_id', sa.String(length=50), nullable=False, comment='网关唯一标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='网关名称'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP 地址'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='固件版本'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: online/offline'),
    sa.Column('capabilities', sa.JSON(), nullable=True, comment='能力列表'),
    sa.Column('cpu_usage', sa.Float(), nullable=True, comment='CPU 使用率 %'),
    sa.Column('memory_usage', sa.Float(), nullable=True, comment='内存使用率 %'),
    sa.Column('disk_usage', sa.Float(), nullable=True, comment='磁盘使用率 %'),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True, comment='最后心跳时间'),
    sa.Column('site_id', sa.Integer(), nullable=True, comment='站点 ID'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_id')
    )
    # 注意: 已移除 Alembic 自动检测到的预存 ALTER COLUMN 变更（SQLite 不支持）
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gateways')
    op.drop_index('ix_datasources_gateway_enabled', table_name='datasources')
    op.drop_table('datasources')
    op.drop_table('datasource_points')
    # ### end Alembic commands ###
